### ISSUE TITLE
dired-subtree?

### ISSUE THREAD

**Issue by dodona2** [jojojames/dired-sidebar#1]
Compiling file /home/dodo/.emacs.d/site-lisp/dired-sidebar.el at Thu Dec  7 07:32:23 2017
dired-sidebar.el:45:1:Error: Cannot open load file: No such file or directory, dired-subtree

**Comment by jojojames** [comment]
Are you cloning it straight from the repo?

You'll also need https://github.com/Fuco1/dired-hacks (dired-subtree) as that's a dependency now.

I recommend installing using melpa as that will automatically download the required dependencies for you.

**Comment by dodona2** [comment]
yes  I'm cloning it straight from the repo

**Comment by jojojames** [comment]
Thanks, yeah you'll need dired-subtree.el from dired-hacks if you're compiling from the repository.

I've updated the readme to reflect that.

**Comment by dodona2** [comment]
I tried it out, going the non-melpa hard way. It has a lot of dependencies but no advantage over neotree.

**Comment by jojojames** [comment]
Thanks, I'm not sure what you mean by 'a lot of dependencies'. It uses dired-subtree which just uses dash.

As for 'no advantage', if you don't already know dired, you might not find this package useful. neotree is a great package too. I recommend using that if you are more comfortable with neotree.
