### ISSUE TITLE
Use most recent used editing window to open files

### ISSUE THREAD

**Issue by finalpatch** [jojojames/dired-sidebar#11]
It would be nice to have the sidebar store the last used editing window (before switching to the sidebar window) and use that window to open files by default (with the enter key).

**Comment by jojojames** [comment]
Good idea.

What do you expect to happen when the sidebar is already up and you transition to it (through something like other-window)? Would you expect that window to be the most recently used window?

A naive approach would be to save the selected window when you toggle the sidebar open and use that window for all files opened. Would that suit your needs or are you looking for something a little smarter?

I'm inclined towards the naive approach myself. Any other approach seems to require a lot of advice on core functions.

I might take a look at neotree's approach sometime, but if you could detail it yourself, that'd be great. Thanks.

**Comment by jojojames** [comment]
Hmnn, I guess (get-mru-window) is a built-in.

**Comment by jojojames** [comment]
Added, feel free to leave comments if it's not working for ya.
