### ISSUE TITLE
Show sidebar on right side

### ISSUE THREAD

**Issue by publicimageltd** [jojojames/dired-sidebar#14]
I might be creating a PR, but right now I have hardly any time, so I just open the issue to document this request: It would make sense to introduce an option to display the sidebar on the right side. As far as I have seen, that just involves changing the alist passed to `display-buffer-in-side-window` within the function `dired-sidebar-show-sidebar`. I just hard wired my desired change, but an option would be cool and easy to introduce.

**Comment by jojojames** [comment]
Thanks, I added an option to customize its appearance.

The additional 'slot' variable is for synergy with https://github.com/jojojames/ibuffer-sidebar so you can also remove it from your configuration.

**Comment by publicimageltd** [comment]
Thanks a lot! That was quick!
