### ISSUE TITLE
Not able to toggle sidebar together with ibuffer-sidebar after opening emacs and providing a file

### ISSUE THREAD

**Issue by nyqvist** [jojojames/dired-sidebar#16]
My use case is like this:
1. open a file with emacs:
`emacs ~/.emacs.d/init.el`
2. toggle dired-sidebar and ibuffer-sidebar:
`M-x +sidebar-toggle`

After this I get the error message: `split-string: Wrong type argument: stringp, nil`, and I can only see dired-sidebar but not ibuffer-sidebar. If I run `M-x +sidebar-toggle` again the ibuffer-sidebar will show but not dired-sidebar, toggling again will make dired-sidebar appear, etc.

If I instead open emacs by itself and not with a filename it works as expected:
`emacs`
`M-x +sidebar-toggle`

My dired-sidebar and ibuffer-sidebar configuration:
```elisp
(use-package dired-sidebar
  :ensure t
  :commands (dired-sidebar-toggle-sidebar)
  :bind ("M-0" . dired-sidebar-jump-to-sidebar)
  :config
  (setq dired-sidebar-theme 'ascii))

(use-package ibuffer-sidebar
  :ensure t
  :commands (ibuffer-sidebar-toggle-sidebar))

(defun +sidebar-toggle ()
  "Toggle both `dired-sidebar' and `ibuffer-sidebar'."
  (interactive)
  (dired-sidebar-toggle-sidebar)
  (ibuffer-sidebar-toggle-sidebar))
```

**Comment by jojojames** [comment]
Can you M-x toggle-debug-on-error and reproduce with the stacktrace attached?

**Comment by nyqvist** [comment]
Here is the backtrace I get:

`Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("/" nil 0)
  split-string(nil "/")
  dired-sidebar-point-at-file("/home/korv/.emacs.d/init.el" "~/.emacs.d/")
  dired-sidebar-toggle-sidebar()
  +sidebar-toggle()
  funcall-interactively(+sidebar-toggle)
  call-interactively(+sidebar-toggle nil nil)
  command-execute(+sidebar-toggle)`

**Comment by jojojames** [comment]
Thanks! I'll take a look as soon as I can.

**Comment by jojojames** [comment]
I'm surprised you're getting "~/.emacs.d/" for the second argument to dired-sidebar-point-at-file.

Can you:

M-: (dired-sidebar-get-dir-to-show) and
M-: (dired-sidebar-sidebar-root)

On OSX, those two calls give me -> "/Users/james/.emacs.d/"

**Comment by nyqvist** [comment]
For both of these calls I get:
"~/.emacs.d/"

I am using emacs version 25.1.1 on Debian if that could be to some help.

**Comment by jojojames** [comment]
Hmnn, I see, running emacs from the terminal gives different values to that default-directory variable.

```
— Variable: default-directory

    The value of this buffer-local variable is the default directory for the current buffer. It should be **an absolute directory name; it may start with ‘~’.** This variable is buffer-local in every buffer. 
```

:(, I added a potential fix. Hope that works for you.

**Comment by nyqvist** [comment]
Thank you for the fix, now it works! :)
