### ISSUE TITLE
Close sidebar when finding a file

### ISSUE THREAD

**Issue by publicimageltd** [jojojames/dired-sidebar#17]
Seeing that `dired-sidebar` is already using its own version of `dired-find-file`, would it be too difficult to implement the option to actually *close* the sidebar when finding a file? I always use the sidebar for navigating to a file, so there's no need for me to keep it open when the target is found.

**Comment by jojojames** [comment]
Just for ~dired-find-file~ right? What about for C-o (opening with ace-window)?

I'll look into it, probably shouldn't be too bad...

**Comment by publicimageltd** [comment]
Opening with C-o is not the same, since the sidebar remains. Thanks for looking into it!

**Comment by jojojames** [comment]
Yup, I'm asking if you'd like that command to *also* close the sidebar.

**Comment by publicimageltd** [comment]
Now I understand. Well, I don't use C-o, but thinking in terms of functionality, it would make sense to either make it "always close on find file, no matter how the target window is selected" or "never close on find file". And while we're speaking about it: A *perfect* solution would toggle that flag if called with prefix. ;-)

**Comment by publicimageltd** [comment]
OK, and here's a related possible feature enhancement: I often open files with external viewers (that is, by pressing & in the dired window). Why not also add automatic closure of the side bar window to this command?

**Comment by jojojames** [comment]
Added an option for this request.

As for 

> I often open files with external viewers (that is, by pressing & in the dired window). Why not also add automatic closure of the side bar window to this command?

I recommend using an advise for the dired functions you want to advise.

It would just be along the lines of:

(advice-add some-function: around your-function)

(defun your-function (f &rest args)
  (if (bound-and-true-p dired-sidebar-mode)
     ;; etc
)

)

**Comment by publicimageltd** [comment]
thanks, works fine! I'll also try the advise.
