### ISSUE TITLE
dired-sidebar won't let me exit emacs

### ISSUE THREAD

**Issue by colinxy** [jojojames/dired-sidebar#2]
Thank you for the package. I really like that I am able to use all my favorite dired command in a convenient sidebar. However, I am having a problem when exiting emacs after some period of usage and it seems to have something to do with `dired-sidebar-refresh-or-schedule-refresh`. The problem happens when I run `(kill-emacs)`, here is the stack trace.

```
Debugger entered--Lisp error: (error "Selecting deleted buffer")
  dired-sidebar-refresh-or-schedule-refresh()
  apply(dired-sidebar-refresh-or-schedule-refresh nil)
  save-buffer()
  write-file("~/.emacs.d/ido.last" nil)
  ido-save-history()
  ido-kill-emacs-hook()
  kill-emacs()
  eval((kill-emacs) nil)
  elisp--eval-last-sexp(t)
  eval-last-sexp(t)
  eval-print-last-sexp(nil)
  funcall-interactively(eval-print-last-sexp nil)
  call-interactively(eval-print-last-sexp nil nil)
  command-execute(eval-print-last-sexp)
```

**Comment by jojojames** [comment]
Thanks for the report and stacktrace.

I added a commit for this. Lemme know if it fixes things for you.

**Comment by colinxy** [comment]
It works, thank you. Really appreciate this package!

**Comment by jojojames** [comment]
Thanks, glad you like it.
