### ISSUE TITLE
Consistently display icons on on subtree

### ISSUE THREAD

**Issue by valignatev** [jojojames/dired-sidebar#21]
Hi! Thanks for a great package, for the most parts it works well for me. One thing is it doesn't display icons when I toggle subtree with `TAB`. For it to happen, I have to turn off and on `all-the-icons-dired-mode`.
Here's my configuration:
```elisp
(use-package dired-sidebar
  :straight t
  :commands (dired-sidebar-toggle-sidebar)
  :config
  ;; Icons for dired
  (use-package all-the-icons
    :straight t
    :config
    ;; all-the-icons doesn't work without font-lock+
    ;; And font-lock+ doesn't have autoloads
    (use-package font-lock+
      :straight (:host github :repo "emacsmirror/font-lock-plus")
      :config (require 'font-lock+))
    (use-package all-the-icons-dired
      :straight t
      :hook (dired-mode . all-the-icons-dired-mode))))
```
I'm using `straight.el` for managing packages, but it works the same way without it.
Also, screenshot for the reference. Before toggling off/on `all-the-icons-dired-mode`
![image](https://user-images.githubusercontent.com/7038954/41504776-12df7f90-723d-11e8-8c1e-41cbbeae863c.png)
After:
![image](https://user-images.githubusercontent.com/7038954/41504781-2db906c4-723d-11e8-9f9b-ef343ea60e1e.png)
What am I missing? :)

**Comment by valignatev** [comment]
Works great, thanks!

**Comment by valignatev** [comment]
Found one more issue with that. Upon initial `dired-sidebar-toggle-sidebar`, if a file I'm currently on is in subfolder, icons on subtree are not displaying. For them to display I have to open/close this subtree, or open/close some other subtree.

**Comment by jojojames** [comment]
Yeah, I have a quick fix laying around for this but I want to take a closer look before making another change.

**Comment by jojojames** [comment]
Tried to address this, lemme know how it goes for you.

**Comment by valignatev** [comment]
Yeah, works great now, thanks!
