### ISSUE TITLE
Defining a derived mode

### ISSUE THREAD

**Issue by akirak** [jojojames/dired-sidebar#23]
Hello,

The major mode of dired-sidebar is `dired-mode`, while that of ibuffer-sidebar is `ibuffer-sidebar-mode`. It would be more convenient if you defined `dired-sidebar-mode` derived from `dired-mode` and used it for dired-sidebar buffers. For example, users can easily define additional keybindings available only in `dired-sidebar-mode`.

**Comment by jojojames** [comment]
Yeah, I wrote ibuffer-sidebar after dired-sidebar so it pulled in some improvements there. 

I'll have to find some motivation to refactor it at some point.. (don't hold your breath).

As for rebinding keys, I think dired-sidebar-mode-map would still work.

**Comment by akirak** [comment]
I personally needed the separate `dired-sidebar-mode' when I created a frame for `dired-mode` using frame-purpose.el. I opened ibuffer-sidebar in the frame so that it would display a list of dired buffers. The sidebar should have included only non-sidebar dired buffers, but it included dired-sidebar buffers as well! As the frame was supposed to display buffers of `dired-mode`, it wouldn't have happened if there had been `dired-sidebar-mode`. 

This is a corner case which sounds so complicated. Okay, there is probably nobody else which experience this case, so if I have time, I will work on it.

> As for rebinding keys, I think dired-sidebar-mode-map would still work.

That sounds good. If will solve most of my needs for now.

**Comment by jojojames** [comment]
> This is a corner case which sounds so complicated. Okay, there will probably be nobody else which actually experience this case, so you may not want to work on it. If I have time, I may or may not implement it.

I think it'd be cool to get it working with frame-purpose.el but I gotta find some time for a refactor first. :) So any help is appreciated for sure..

**Comment by jojojames** [comment]
Found some time to do this, we can continue the discussion in the PR.
