### ISSUE TITLE
Icons for dired-sidebar-theme 'vscode very tiny

### ISSUE THREAD

**Issue by terlar** [jojojames/dired-sidebar#26]
I tried the new `vscode` theme but somehow it renders the icons very small:

![screen shot 2018-08-30 at 05 54 20](https://user-images.githubusercontent.com/280235/44828709-77457280-ac19-11e8-9d5f-fe17d45a2435.png)

The small dots in different colors you see are the actual icons. Any idea what could be causing this?

I am running GNU Emacs 27.0.50 on macOS.

**Comment by jojojames** [comment]
Can you post the config?

**Comment by terlar** [comment]
For dired? Otherwise I could spend some time into making a minimal reproduction step via `emacs -Q`.

```
   (use-package dired
     :straight nil
     :hook
     (dired-mode . hl-line-mode)
     (dired-mode . dired-hide-details-mode)
     (dired-mode . +dired-mode-faces)
     :custom
     (dired-listing-switches "-al --group-directories-first")
     ;; Always copy/delete recursively
     (dired-recursive-copies  'always)
     (dired-recursive-deletes 'top)
     :init
     (defun +dired-mode-faces ()
       (face-remap-add-relative 'hl-line
                                :background (face-background 'isearch))))
```

**Comment by jojojames** [comment]
For dired-sidebar, and vscode-icon.

**Comment by jojojames** [comment]
Minimal repro not needed, just the two pieces.

**Comment by jojojames** [comment]
Contents of vscode-icon folder in elpa?

**Comment by jojojames** [comment]
These are the contents of vscode-icon when I package-install it.

```
vscode-icon-20180827.402/ $ ls
icons/                    vscode-icon-pkg.el        vscode-icon.elc
vscode-icon-autoloads.el  vscode-icon.el
vscode-icon-20180827.402/ $ ls icons
128/ 23/
vscode-icon-20180827.402/ $ 
```

**Comment by terlar** [comment]
Yes that directory is there, a bit hard to spot among all those icons:
```
  vscode-icon
$ ls
icons/  vscode-icon-autoloads.el  vscode-icon-autoloads.elc  vscode-icon.el@  vscode-icon.elc
$ cd icons/
  vscode-icon/icons
$ ls
128/  23/
$ 
```

This is the build directory of the package (I'm using straight.el). Before I listed the source directory, however it also includes both those icon folders. But I guess this is the place that it uses.

**Comment by jojojames** [comment]
I think this is an issue with how straight pulls down the icons and how vscode-icon.el looks for the icons.

You can try a regular package-install and use vscode-icon there and see if that's true.

For working around it, I think you just need to specify the correct dependencies to pull down with straight.

**Comment by terlar** [comment]
This is a full reproducible config and setup which causes the problem for me:
```emacs-lisp
(setq straight-recipes-gnu-elpa-use-mirror t)
(eval-and-compile
  (defvar bootstrap-version)
  (let ((bootstrap-file
         (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
        (bootstrap-version 5))
    (unless (file-exists-p bootstrap-file)
      (with-current-buffer
          (url-retrieve-synchronously
           "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
           'silent 'inhibit-cookies)
        (goto-char (point-max))
        (eval-print-last-sexp)))
    (load bootstrap-file nil 'nomessage)))

(setq straight-cache-autoloads t
      straight-use-package-by-default t
      straight-vc-git-default-protocol 'https
      straight-vc-git-force-protocol t)

(eval-and-compile
  (straight-use-package 'use-package)
  (require 'use-package)
  (setq use-package-always-defer t))

(use-package dired
  :straight nil
  :hook
  (dired-mode . hl-line-mode)
  (dired-mode . dired-hide-details-mode)
  :custom
  (dired-listing-switches "-al --group-directories-first")
  ;; Always copy/delete recursively
  (dired-recursive-copies  'always)
  (dired-recursive-deletes 'top))

(use-package dired-sidebar
  :demand t
  :custom
  (dired-sidebar-theme 'vscode))

(use-package dired-subtree
  :demand t
  :custom
  (dired-subtree-use-backgrounds nil)
  (dired-subtree-line-prefix "     "))

(use-package vscode-icon :demand t)
```

I will try a regular package-install.

**Comment by terlar** [comment]
Same issue with plain `package.el`/`use-package`:

```emacs-lisp
(setq package-enable-at-startup nil
      package-archives
      '(("melpa" . "http://melpa.milkbox.net/packages/")
        ("gnu" . "http://elpa.gnu.org/packages/")))

(require 'package)
(package-initialize)
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(require 'use-package)
(setq use-package-always-ensure t)

(use-package dired-sidebar
  :demand t
  :custom
  (dired-sidebar-theme 'vscode))

(use-package dired-subtree
  :demand t
  :custom
  (dired-subtree-use-backgrounds nil)
  (dired-subtree-line-prefix "     "))

(use-package vscode-icon :demand t)
```

**Comment by jojojames** [comment]
<img width="1246" alt="screenshot 2018-08-31 01 45 39" src="https://user-images.githubusercontent.com/1227856/44902736-9eef1600-acbf-11e8-8567-95d34fdd8a5d.png">

Works for me off emacs -Q (emacs 27) on OSX.

Can you double check the icons are displaying properly outside of emacs?

**Comment by terlar** [comment]
Yes, it does, even inside Emacs itself:
<img width="721" alt="screen shot 2018-08-31 at 11 01 57" src="https://user-images.githubusercontent.com/280235/44903614-4cd4e180-ad0d-11e8-9741-a9ff5cce10b2.png">

Really strange, I have no idea what could be the reason. Are you running on retina or not?

**Comment by jojojames** [comment]
I'm on a macbook retina (it works on a bigger display too).

You can try running this function.

```
(defun vscode-icon-for-file (file)
  "Return an vscode icon image given FILE.

Icon Source: https://github.com/vscode-icons/vscode-icons"
  (let ((default-directory
          (if (image-type-available-p 'imagemagick)
              (concat vscode-icon-dir "128/")
            (concat vscode-icon-dir
                    (number-to-string vscode-icon-size) "/"))))
    (if (file-directory-p file)
        (vscode-icon-dir file)
      (vscode-icon-file file))))
```

https://github.com/jojojames/vscode-icon-emacs (see the scratch buffer in this link) to see what those functions insert into the buffer.

**Comment by terlar** [comment]
I guess we could move this issue to the `vscode-icon` package. I just tried updating that function and inserting the images. Same result (super tiny). Doesn't matter what resolution/screen/zoom I use for the font.
![screen shot 2018-08-31 at 17 01 10](https://user-images.githubusercontent.com/280235/44920247-b7067a00-ad3f-11e8-9183-893e740e774e.png)

**Comment by terlar** [comment]
I'm using this build of Emacs (https://emacsformacosx.com/emacs-builds/Emacs-2018-06-13_01-40-16-b8478b2ab7ad19c629da9c6b0dfd9a6544a6acee-universal.dmg) from https://emacsformacosx.com/builds

Which one are you running?

**Comment by terlar** [comment]
I have found something suspicious, if I inspect those variables I see the following:
```
json-image’s value is
(image :type png :file "/Users/terje.larsen/emacsjail/.emacs.d/elpa/vscode-icon-20180827.402/icons/23/file_type_json.png" :scale 0.1796875 :ascent center)
```

The scale looks very tiny. I just tried updating that variable and setting the :scale keyword to 1.0 and that looks good. What is determining the scale?

**Comment by terlar** [comment]
I did some experimentation and for me the sizes are the opposite.

These are my results:
![screen shot 2018-08-31 at 17 38 57](https://user-images.githubusercontent.com/280235/44922130-ca681400-ad44-11e8-90e8-f1ad52f0a466.png)

**Comment by jojojames** [comment]
This is the entry point function:

```
(defun vscode-icon-for-file (file)
  "Return an vscode icon image given FILE.

Icon Source: https://github.com/vscode-icons/vscode-icons"
  (let ((default-directory
          (if (image-type-available-p 'imagemagick)
              (concat vscode-icon-dir "128/")
            (concat vscode-icon-dir
                    (number-to-string vscode-icon-size) "/"))))
    (if (file-directory-p file)
        (vscode-icon-dir file)
      (vscode-icon-file file))))
```

Can you check if you have imagemagick support? It looks like your emacs supports scaling icons without imagemagick support.

**Comment by jojojames** [comment]
I added a commit in vscode-icon for this. It looks like there was a commit on the emacs 27 / master branch that adds resizing/rescaling handling to emacs without imagemagick.

Lemme know if this still doesn't work for you and reopen in vscode repo if so.

> Anyways, thanks for helping debug this, I now understand more about the image rendering inside Emacs.

Thanks for reporting and providing good debug info!
