### ISSUE TITLE
Sidebar not reloaded when changing folders

### ISSUE THREAD

**Issue by arj03** [jojojames/dired-sidebar#28]
Hi

First of all, thanks for a great project. This is exactly what I need to wrangle js projects with million of files scattered everywhere :) I've tried installing this module (20181003.716) from melpa and using it in my emacs with the following config:

```
(use-package dired-sidebar
  :bind (("C-x C-n" . dired-sidebar-toggle-sidebar))
  :ensure t
  :commands (dired-sidebar-toggle-sidebar)
  :init
  (add-hook 'dired-sidebar-mode-hook
            (lambda ()
              (unless (file-remote-p default-directory)
                (auto-revert-mode))))
  :config
  (push 'toggle-window-split dired-sidebar-toggle-hidden-commands)
  (push 'rotate-windows dired-sidebar-toggle-hidden-commands)

  (setq dired-sidebar-subtree-line-prefix "__")
  (setq dired-sidebar-theme 'spacemacs)
  (setq dired-sidebar-use-term-integration t)
  (setq dired-sidebar-use-custom-font t))
```

But it appears that when I change folders by navigating to either `..` or a folder name then dired-sidebar looses where it was at and doesn't refresh the current folder. So I have to manually press `g` to make it refresh. To be able to navigate again. I'm using emacs 26.1. Let me know if

**Comment by jojojames** [comment]
> First of all, thanks for a great project. This is exactly what I need to wrangle js projects with million of files scattered everywhere :)

Thanks! Glad it's helpful for you.

> (setq dired-sidebar-theme 'spacemacs)

Does this do anything special for you?

> But it appears that when I change folders by navigating to either .. or a folder name then dired-sidebar looses where it was at and doesn't refresh the current folder. So I have to manually press g to make it refresh. To be able to navigate again. I'm using emacs 26.1. Let me know if

Hmnn! I'm not sure what you're describing. Could you do a quick screencast?

We might not have to go that far but a quick emacs -Q recipe would be great too!

Thanks.

**Comment by jojojames** [comment]
Lemme know if you find the time to return to this! Thanks.
