### ISSUE TITLE
Cannot kill buffer: “Marker does not point anywhere”

### ISSUE THREAD

**Issue by ChoppinBlockParty** [jojojames/dired-sidebar#29]
For some reasons I hit the error in `dired-current-directory`. Please, see [this stackoverflow question](https://stackoverflow.com/questions/52724679/cannot-kill-buffer-marker-does-not-point-anywhere) for more details.

Very hard to reproduce. I reproduced it once, then failed to reproduce it again. But it somehow all around the following flow.

* I open a bar in `A` directory.
* Call `dired-view-file` on some child directories of it (this opens a dired buffer outside the bar).
* Close the bar, choose a file from the dired buffer. This file is located in some project.
* I open a bar again, it opens a child directory `B` of directory `A`.
* I repeat the steps again an somehow its stuck.

I think the main problem is that at the end I have two or more dired-sidebar buffers, it also could be relevant to opening sidebar buffers inside a regular window, not really on a side.

If I find anything more I will tell you.

**Comment by jojojames** [comment]
Would appreciate an emacs -Q if you ever find the chance.

**Comment by fasheng** [comment]
Same problem here, I found caused by the all-the-icons theme, but following code works fine:
```elisp
(setq dired-sidebar-theme 'none) ; none, ascii, nerd all works but icon
(add-hook 'dired-mode-hook #'all-the-icons-dired-mode)
```

And the backtrace:
```
Debugger entered--Lisp error: (error "Marker does not point anywhere")
  dired-current-directory()
  dired-get-filename(nil t)
  dired-save-positions()
  #f(compiled-function (&optional arg noconfirm) "Reread the Dired buffer.\nMust also be called after `dired-actual-switches' have changed.\nShould not fail even on completely garbaged buffers.\nPreserves old cursor, marks/flags, hidden-p.\n\nDired sets `revert-buffer-function' to this function.  The args\nARG and NOCONFIRM, passed from `revert-buffer', are ignored." #<bytecode 0x15b67fd>)()
  apply(#f(compiled-function (&optional arg noconfirm) "Reread the Dired buffer.\nMust also be called after `dired-actual-switches' have changed.\nShould not fail even on completely garbaged buffers.\nPreserves old cursor, marks/flags, hidden-p.\n\nDired sets `revert-buffer-function' to this function.  The args\nARG and NOCONFIRM, passed from `revert-buffer', are ignored." #<bytecode 0x15b67fd>) nil)
  dired-revert()
  dired-sidebar-revert(t nil)
  revert-buffer(t)
  funcall-interactively(revert-buffer t)
  call-interactively(revert-buffer nil nil)
  command-execute(revert-buffer)
```

Hope helps.

**Comment by jojojames** [comment]
@fasheng Are you saying this:

```
(setq dired-sidebar-theme 'none) ; none, ascii, nerd all works but icon
(add-hook 'dired-mode-hook #'all-the-icons-dired-mode)
```

works? (As in the problem does not reproduce.)?

**Comment by fasheng** [comment]
Yes, a workaround for icons theme for dired-sidebar here. And problem never reproduce here.

**Comment by jojojames** [comment]
@fasheng Did you have a repro when you set dired-sidebar-theme to 'icons? The original report states it's hard to reproduce.

**Comment by fasheng** [comment]
At first, I did some hack work to keep dired-sidebar only exist one buffer instance though user may switch to multiple directories. But after some more debug work, a simple reproduce steps was found:
1. Switch to any buffer, and run `dired-sidebar-toggle-with-current-directory`
2. After dired-sidebar shown, kill the sidebar buffer
3. run `dired-sidebar-toggle-with-current-directory` again in previous buffer, then will show "Marker does not point anywhere" error.

And full config in init.el:
```elisp
(require 'package)
(add-to-list 'package-archives
             '("melpa" . "http://melpa.milkbox.net/packages/") t)
(add-to-list 'package-archives
             '("melpa-stable" . "https://stable.melpa.org/packages/") t)
(package-initialize)

(use-package dired-sidebar
  :defer t
  :bind (("<f3>" . #'dired-sidebar-toggle-with-current-directory))
  :config
  (setq dired-sidebar-theme 'icons))
```

So this mean It occurs even all other packages disabled, you could have a try.

**Comment by jojojames** [comment]
Thanks @fasheng for the repro. I added something for this. Please try it out and reopen if it doesn't work @fasheng @ChoppinBlockParty .

**Comment by fasheng** [comment]
Great, works here!
