### ISSUE TITLE
Feature Request: Command to launch full dired buffer from sidebar

### ISSUE THREAD

**Issue by justbur** [jojojames/dired-sidebar#3]
I think it would be nice to have a command that hides the sidebar and opens a corresponding dired buffer. Perhaps it would be nice to convert an existing dired buffer into a sidebar one too. 

EDIT: I guess the second one is straightforward using existing commands, but the first one doesn't seem to be.

**Comment by justbur** [comment]
Never mind. I just figured out an easy way to do what I want.

**Comment by jojojames** [comment]
@justbur Could you list your approaches?

That type of functionality sounds good.

**Comment by justbur** [comment]
I have some ideas, but all I was really looking for was a way to quickly check the modification times of the files. I realized that `o` on `.` works for this purpose. `o` is a little weird though, because I sort of expect it to open the buffer in the same window that `RET` does, but it creates a new window for me. 

I just opened one pr with a small tweak to find-file, but there are other ways to approach this.
