### ISSUE TITLE
Side tree dedicated window not honoured

### ISSUE THREAD

**Issue by md1023** [jojojames/dired-sidebar#31]
I've switched to Emacs 26.1 and now when I press C-x-1 (delete-other-windows) my sidebar hides. It didn't happen on previous Emacs 24. What can I do, maybe some config issue?

**Comment by jojojames** [comment]
Sorry I missed this.

It looks like it's not a bug but I've added a customization option to get the functionality you want.

```
defcustom dired-sidebar-no-delete-other-windows nil
```

You'll have to set it to t to get it working.

Lemme know if it doesn't work for ya.
