### ISSUE TITLE
Highlight active buffer in a tree

### ISSUE THREAD

**Issue by md1023** [jojojames/dired-sidebar#32]
Is it possible to highlight file name in a sidebar tree for a file that is in current buffer?

**Comment by jojojames** [comment]
You mean follow the current buffer with the sidebar and then highlight where the sidebar currently is?

**Comment by md1023** [comment]
yes! :)

**Comment by jojojames** [comment]
I think it should be doable with:

```
(defcustom dired-sidebar-should-follow-file nil
  "Refresh sidebar to match current file."
  :type 'boolean
  :group 'dired-sidebar)
```

to get the follow part. Highlighting, I would've though hl-line-mode could do it. If I find some free time, I'll look into it more. No timetables though :)

**Comment by jojojames** [comment]
I'll close this for now and come back to it if I ever find the motivation. (It's low hanging fruit for me at this point.)

PRs (or extra research) welcome in the meantime.
