### ISSUE TITLE
re-search-forward fails

### ISSUE THREAD

**Issue by lshoravi** [jojojames/dired-sidebar#33]
Toggling dired-sidebar-toggle-sidebar always fails.

Debug error:
``` emacs-lisp
Debugger entered--Lisp error: (search-failed "^.*[[:space:]]mandatory")
  re-search-forward("^.*[[:space:]]mandatory")
  dired-sidebar-point-at-file("/home/linus/Documents/UU/Datorsystem/m2/module-2/mandatory/src/signals.c" "/home/linus/Documents/UU/Datorsystem/m2/module-2/")
  dired-sidebar-toggle-sidebar()
  funcall-interactively(dired-sidebar-toggle-sidebar)
  call-interactively(dired-sidebar-toggle-sidebar nil nil)
  command-execute(dired-sidebar-toggle-sidebar)
```

**Comment by jojojames** [comment]
Repro steps will help here.

**Comment by lshoravi** [comment]
Sorry!

This happends whenever I toggle dired-sidebar in the directory named
"/home/linus/Documents/UU/Datorsystem/m2/module-2/mandatory/src/pipeline.c".
That's literally it.

Den lör 9 feb. 2019 kl 19:16 skrev James N <notifications@github.com>:

**Comment by lshoravi** [comment]
Investigating some more reveals that it's golden-ratio-mode that's destroying the window somehow. Disabling it fixes all issues.

I'll file an issue in that repository.

**Comment by jojojames** [comment]
> I'll file an issue in that repository.

Sounds good. I'm open to looking at it on this side of things too, to see if there's anything dired-sidebar can do to play nice with golden-ratio-mode.
