### ISSUE TITLE
refresh after changing edited file

### ISSUE THREAD

**Issue by qleguennec** [jojojames/dired-sidebar#34]
Hello,

I'm trying to use `dired-sidebar-special-refresh-commands` to refresh the sidebar when I change the edited file of the current buffer. I usually change file with `counsel-projectile`. I tried adding `counsel-projectile` to `dired-sidebar-special-refresh-commands` but it doesn't work.

Thanks.

**Comment by jojojames** [comment]
What do you expect to happen after 'refresh'?, just so I'm clear.

**Comment by qleguennec** [comment]
Refresh the `dired-sidebar` buffer.

**Comment by jojojames** [comment]
You're doing doing me any favors here. :)

Anyways, I don't think we are on the same page with regards to what 'refresh' means. 'Refresh' in this case just triggers 'revert-buffer' on the current dired buffer. It won't move dired to the current directory of the file you just entered.

If what you're looking for is the latter, than that's not what the setting is for.
