### ISSUE TITLE
cannot toggle subtree in emacs27

### ISSUE THREAD

**Issue by BooAA** [jojojames/dired-sidebar#35]
emacs version : 27.0.50
config : 
```emacs-lisp
;; no all-the-icons, no projectile, just dired-sidebar + dired-subtree
(use-package dired-sidebar
  :bind ("C-x C-n" . dired-sidebar-toggle-sidebar))

```
problem description : dired-sidebar-subtree-toggle doesn't work

GIF 
![Peek 2019-03-14 12-55](https://user-images.githubusercontent.com/32809182/54332293-81c8d600-4658-11e9-8edb-546644e31ab0.gif)

The line number will increase if keep pressing tab, but nothing has shown. And the next item indent when toggle subtree first time.

By the way, dired-subtree works find in emacs27
![Peek 2019-03-14 13-00](https://user-images.githubusercontent.com/32809182/54332486-572b4d00-4659-11e9-9182-3927531d7da4.gif)

The package is awesome, since I love dired and prefer something based on it to manage files in project.  Another question off topic, is it possible to switch directory without creating new buffers? When I pressed "a"(dired-find-alternate-file), it says "cannot make side window  the only window".

**Comment by jojojames** [comment]
> When I pressed "a"(dired-find-alternate-file), it says "cannot make side window the only window".

Can you create a separate issue so I can track it. I'll look into it.

emacs -Q and specific emacs 27 commit you're on helps. I'm on emacs 27 (built last week) and it works for me.

**Comment by BooAA** [comment]
I was on commit  ``` fbe87d0f8f8878b30b1dfe74f7eb369b569bab6b``` before, and I just update to the newest commit and test with emacs -Q, but it doesn't fix the problem.

I'm using ubuntu 18.04, with emacs built with ```./configure --with-mailutils --with-xwidgets```

**Comment by jojojames** [comment]
Hmnn, not sure what's going on, do you have an OSX machine? It works for me on emacs 27 (latest commit) on OSX. I don't won't have access to a linux machine for 1-2 months to to take a hard look at it.

Alternatively, the first commit on emacs 27 that breaks this would be great.

**Comment by BooAA** [comment]
Sorry, I don't have access to OSX either.  Strangely, I have tested on ```emacs26 -Q``` and it have the same problem. 

![Peek 2019-03-15 22-43](https://user-images.githubusercontent.com/32809182/54439515-e62c8800-4773-11e9-9de8-250ee1fc5475.gif)

I have no clue.......

**Comment by jojojames** [comment]
You sure that's an emacs -Q? Make sure you move your .emacs.d directory somewhere else too. It looks like you're pulling dired-sidebar from your elpa folder.

**Comment by BooAA** [comment]
Does it matter whether I move .emacs.d to somewhere else or not? Since ```emacs -Q``` won't load init file  hence it will be a clean emacs without any config I think. I really pull dired-sidebar from the original elpa folder but I didn't load other package yet so I think it might be ok? (I do that since I have a bad internet environment and I don't want to download package again yesterday)

I have renamed my original .emacs.d to .emacs.d.bk and tested with ```emacs -Q```  again this time and it's still the same. 

emacs26 : 
![Peek 2019-03-16 11-29](https://user-images.githubusercontent.com/32809182/54470191-d39b6880-47de-11e9-8c21-4f1e9e446569.gif)

emacs27
![Peek 2019-03-16 11-32](https://user-images.githubusercontent.com/32809182/54470231-3856c300-47df-11e9-9fb3-39e964b8a169.gif)


If I do something wrong on testing please let me know, thanks.

**Comment by jojojames** [comment]
>  I really pull dired-sidebar from the original elpa folder but I didn't load other package yet so I think it might be ok? (I do that since I have a bad internet environment and I don't want to download package again yesterday)

Nope, because it's hard tell which packages are using what.

**Comment by jojojames** [comment]
Also when doing emacs -Q, start with emacs -Q on the emacs 27 binary and compile dired-sidebar (and its dependencies from melpa). Sometimes there are bytecode differences between the emacs versions and using dired-sidebar compiled from emacs 26 may not work with emacs 27.

**Comment by fasheng** [comment]
I don't use emacs 27, but "cannot make side window the only window" should be caused by `display-buffer-in-side-window` which is not very friendly in some cases, for example you want toturn off `dired-hide-details-mode` and  `delete-other-windows` in dired-sidebar to make it looks like a normal dired buffer, this error will occurs.

Maybe we could use `split-window`/`window--display-buffer` instead just like `imenu-list` did.
