### ISSUE TITLE
Cannot open load file: No such file or directory: dired-subtree

### ISSUE THREAD

**Issue by g3ntleman** [jojojames/dired-sidebar#37]
After installing dired-subtree in addition to projectile, I was hoping to show the projectile directory in dired. However, M-x dired-sidebar-toggle-sidebar delivers above error.

I feel, I might do something stupid.

I copied the  (use-package ...) macro from the Readme into my .emacs file. Emacs is 26.1 for mac OS.

**Comment by jojojames** [comment]
emacs -Q with use-package will help a lot, thanks!

**Comment by jojojames** [comment]
Feel free to open with repro when you get a chance.
