### ISSUE TITLE
dired-sidebar removes icons from all-the-icons-dired

### ISSUE THREAD

**Issue by MaxSt** [jojojames/dired-sidebar#41]
First of all, thanks for this cool package! :+1:

I'm using dired with [all-the-icons-dired](https://github.com/jtbm37/all-the-icons-dired). When I start emacs and open dired, I see the icons in dired. However, when I open dired anytime after `(dired-sidebar-toggle-sidebar)`, the icons in dired are gone. When I start emacs and don't open dired-sidbar, the icons are showing up in dired. Is dired-sidebar setting any variables that could prevent displaying the icons in all-the-icons-dired?

**Comment by jojojames** [comment]
Thanks for the report.

I added something for this. Let me know how it goes.

**Comment by MaxSt** [comment]
:+1: Thank you, the icons now show up in dired :tada:.
