### ISSUE TITLE
side bar doesnt show up

### ISSUE THREAD

**Issue by aviikc** [jojojames/dired-sidebar#42]
`Debugger entered--Lisp error: (wrong-type-argument symbolp (quote rotate-windows))
  gv-get(((quote rotate-windows) dired-sidebar-toggle-hidden-commands) #[514 "\211\301\300E!\207" [v cons] 6 "\n\n(fn GETTER SETTER)"])
  #[514 "\2119\203
\300\301EE\207\302\303!\210\304!\203\211\202\305\306!\307\310\311\312\313\314!\315\"\316\317%\"=\2039\211\202@\320DC\"\207" [setq cons require macroexp macroexp-copyable-p make-symbol "v" gv-get make-byte-code 514 "\211\301\300E!\207" vconcat vector [cons] 6 "\n\n(fn GETTER SETTER)" macroexp-let*] 12 2445880](((quote toggle-window-split) dired-sidebar-toggle-hidden-commands) ((quote rotate-windows) dired-sidebar-toggle-hidden-commands))
  (push ((quote toggle-window-split) dired-sidebar-toggle-hidden-commands) ((quote rotate-windows) dired-sidebar-toggle-hidden-commands))
  (progn (push ((quote toggle-window-split) dired-sidebar-toggle-hidden-commands) ((quote rotate-windows) dired-sidebar-toggle-hidden-commands)) (setq (dired-sidebar-subtree-line-prefix "__") (dired-sidebar-theme (quote vscode)) (dired-sidebar-use-term-integration t) (dired-sidebar-use-custom-font t)) t)
  (condition-case err (progn (push ((quote toggle-window-split) dired-sidebar-toggle-hidden-commands) ((quote rotate-windows) dired-sidebar-toggle-hidden-commands)) (setq (dired-sidebar-subtree-line-prefix "__") (dired-sidebar-theme (quote vscode)) (dired-sidebar-use-term-integration t) (dired-sidebar-use-custom-font t)) t) ((debug error) (funcall use-package--warning9 :config err)))
  (condition-case-unless-debug err (progn (push ((quote toggle-window-split) dired-sidebar-toggle-hidden-commands) ((quote rotate-windows) dired-sidebar-toggle-hidden-commands)) (setq (dired-sidebar-subtree-line-prefix "__") (dired-sidebar-theme (quote vscode)) (dired-sidebar-use-term-integration t) (dired-sidebar-use-custom-font t)) t) (error (funcall use-package--warning9 :config err)))
  (lambda nil (condition-case-unless-debug err (progn (push ((quote toggle-window-split) dired-sidebar-toggle-hidden-commands) ((quote rotate-windows) dired-sidebar-toggle-hidden-commands)) (setq (dired-sidebar-subtree-line-prefix "__") (dired-sidebar-theme (quote vscode)) (dired-sidebar-use-term-integration t) (dired-sidebar-use-custom-font t)) t) (error (funcall use-package--warning9 :config err))))()
  eval-after-load-helper("/home/aviik/.emacs.d/straight/build/dired-sidebar/dired-sidebar.elc")
  run-hook-with-args(eval-after-load-helper "/home/aviik/.emacs.d/straight/build/dired-sidebar/dired-sidebar.elc")
  do-after-load-evaluation("/home/aviik/.emacs.d/straight/build/dired-sidebar/dired-sidebar.elc")
  (dired-sidebar-toggle-sidebar)
  sidebar-toggle()
  funcall-interactively(sidebar-toggle)
  call-interactively(sidebar-toggle nil nil)
  command-execute(sidebar-toggle)`

**Comment by aviikc** [comment]
![Screenshot_2019-06-29_08-05-49](https://user-images.githubusercontent.com/46831655/60378747-f6c3ee00-9a44-11e9-8ea2-4cdf897a2401.png)

**Comment by jojojames** [comment]
You can try removing the push line. That seems sketchy.

**Comment by jojojames** [comment]
Feel free to reopen once you have more info, thanks!
