### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by bbatsov** [jojojames/dired-sidebar#44]
That's needed for the project to be available on MELPA Stable. Seems there were no official releases since the project was started.

**Comment by jojojames** [comment]
Done, thanks.

**Comment by bbatsov** [comment]
Thanks for the quick response! One small thing - I'd suggest you to use some numbering starting from `0.1.0`, so you can at least denote bugfix releases down the road. Anyways, that's totally up to you.

**Comment by jojojames** [comment]
Sure sounds good, thanks for the suggestion!
