### ISSUE TITLE
New file from current path

### ISSUE THREAD

**Issue by iris-garcia** [jojojames/dired-sidebar#52]
I would like to create a new file in the directory I have my pointer in the same way as I can create a new directory.
Couldn't find any map to achieve that.

**Comment by jojojames** [comment]
I do something like this:

```
(defun j-dired-find-file ()
    "Like `find-file' but with `default-directory' set to the
one specified by listing header."
    (interactive)
    (let ((default-directory (dired-current-directory)))
      (call-interactively #'find-file)))

  (with-eval-after-load 'evil
    (evil-define-key 'normal dired-mode-map
      (kbd "C-x C-f") 'j-dired-find-file))

```

Hesitant to default override the key in this package though. If you have a good idea on a good keybind, PR welcome.

**Comment by iris-garcia** [comment]
Thank you @jojojames!
