### ISSUE TITLE
Themes interact poorly with method of renaming dired buffer

### ISSUE THREAD

**Issue by Amorymeltzer** [jojojames/dired-sidebar#58]
I've use something like the following to [rename by dired buffers](https://emacs.stackexchange.com/a/2154/2051):

```elisp
(add-hook 'dired-after-readin-hook
          (lambda ()
            (rename-buffer (generate-new-buffer-name (concat "dired: " dired-directory)))))
```

When I set `dired-sidebar-theme` this goes totally haywire, running in an unbreakable loop until I crash Emacs.  It happens for `ascii`, `nerd`, and `vscode`; I'm on the OSX terminal so `icons` appears to fall back to `none`, but I imagine it might happen there too?

No worries if you want to close this as it's not an issue with dired-sidebar directly, but wanted to open it in case there was something interesting to be done.

**Comment by DivineDominion** [comment]
I  noticed that `dired-sidebar` doesn't cache a reference to the sidebar window. Maybe that would help in the long run? @jojojames Currently, the expected buffer name is used to dynamically select the window instead.

**Comment by jojojames** [comment]
Wouldn't be opposed to something if you can cook something up @DivineDominion
