### ISSUE TITLE
Crash in directory managed by Emacs EDE project

### ISSUE THREAD

**Issue by FabArd** [jojojames/dired-sidebar#61]
Dired-sidebar crash when you try to use it in a directory managed by EDE emacs project.

https://www.gnu.org/software/emacs/manual/html_mono/ede.html

I tried to analyze the problem: it is situated In dired-sidebar-sidebar-root function at line 795.
You call the function project-current (line 806) and in the case of an EDE project it retrun a single value (not a list).
Just after (line 807) there is a (cdr project).

**Comment by jojojames** [comment]
Can you detail a list of steps to reproduce this? I am not familiar with EDE. Alternatively, a PR will be welcome.

**Comment by FabArd** [comment]
I just follow the example in the link above : 

2 EDE Mode
EDE is implemented as a minor mode, which augments other modes such as C mode, and Texinfo mode. You can enable EDE for all buffers by running the command global-ede-mode, or by putting this in your init file:

(global-ede-mode t)

Activating EDE adds a menu named ‘Development’ to the menu bar. This menu provides several menu items for high-level EDE commands. These menu items, and their corresponding keybindings, are independent of the type of project you are actually working on.

3 Quick Start
Once you have EDE enabled, you can create a project. This chapter provides an example C++ project that will create Automake files for compilation.

3.1 Step 1: Create root directory
First, lets create a directory for our project. For this example, we’ll start with something in /tmp.

C-x C-f /tmp/myproject/README RET
M-x make-directory RET RET
Now put some plain text in your README file to start.

Now, lets create the project:

M-x ede-new RET Automake RET myproject RET
Nothing visible happened, but if you use dired to look at the directory, you should see this:

  /tmp/myproject:
  total used in directory 32 available 166643476
  drwxr-xr-x  2 zappo users  4096 2012-02-23 22:10 .
  drwxrwxrwt 73 root  root  20480 2012-02-23 22:10 ..
  -rw-r--r--  1 zappo users   195 2012-02-23 22:10 Project.ede
  -rw-r--r--  1 zappo users    10 2012-02-23 22:09 README

3.2 Step 2: Create Subdirectories and Files
We’ll make a more complex project, so use dired to create some more directories using the + key, and typing in new directories:

+ include RET
+ src RET

At this point if I launch dired-sidebar Emacs show this message : 
dired-sidebar-get-dir-to-show: Wrong type argument: listp, #s(ede-proj-project "/tmp/myproject/Project.ede" nil "myproject" "1.0" "/tmp/myproject/" 606230 nil nil nil ...)

**Comment by jojojames** [comment]
Took a while but hopefully fixed. Thanks for the report and the repro instructions.
