### ISSUE TITLE
always highlight current file

### ISSUE THREAD

**Issue by jiacai2050** [jojojames/dired-sidebar#65]
when dired-sidebar is active buffer, `hl-line` works as expected, but when I open a file from sidebar, dired-sidebar will not highlight current file anymore (we can only recenter it), is there any methods to always highlight current file?

**Comment by DivineDominion** [comment]
@jiacai2050 Not a fix _here_, but I personally use `lin-mode` by @protesilaos to highlight lines _as selections_ (opposed to subtly highlighting where the point is) and that works really well:  https://gitlab.com/protesilaos/lin

**Comment by jiacai2050** [comment]
@DivineDominion lin works as well, thanks for your help.

**Comment by protesilaos** [comment]
> It stills unhighlight dired-sidebar when it's not the active buffer in lin-mode

I haven't tested this: check `hl-line-sticky-flag` and its global variant (depending on how you set things up).

**Comment by jiacai2050** [comment]
I use global version. it will lost highlight even global-hl-line-sticky-flag is t

![highlight](https://user-images.githubusercontent.com/3848910/158086179-787cc1fc-0461-48f4-9a10-e49e85e368bf.gif)

**Comment by protesilaos** [comment]
It works on my end.  You problably need to restart the `global-hl-line-mode` after setting the sticky flag to non-nil.

![2022-03-14_11:01:17_1382x696](https://user-images.githubusercontent.com/12828033/158139129-de9706f8-be86-404c-a590-4b35e7757308.png)

At any rate, this is not a `dired-sidebar` bug.

**Comment by jiacai2050** [comment]
@protesilaos I find the root cause. 

When `dired-sidebar-should-follow-file` is t, it seems that dired-sidebar refresh buffer, no it will unhighlight current line, set it to nil solve my problem.

> At any rate, this is not a dired-sidebar bug.

Of course, this is rather a user's problem.

**Comment by jiacai2050** [comment]
![image](https://user-images.githubusercontent.com/3848910/158201990-ca462ed3-a7dd-4d8b-b9d9-84c6dd07f046.png)

My Emacs looks like other 'modern' editors now.

**Comment by DivineDominion** [comment]
`dired-sidebar-should-follow-file` is `nil` on my end and the highlight disappears after a while, too. Hm.

**Comment by DivineDominion** [comment]
@jiacai2050 I don't have `global-hl-line-mode` mode turned on, only buffer-local, mostly for lin.el :/

**Comment by cxa** [comment]
I don't know why `dired-sidebar-revert` breaks `hl-line-mode`. I use the following workaround, which works fine for me:

```elisp
(advice-add 'dired-sidebar-revert :after (lambda (&rest _r) (hl-line-highlight)))
```
