### ISSUE TITLE
Integrate with project.el

### ISSUE THREAD

**Issue by Ergus** [jojojames/dired-sidebar#68]
Hi:

Emacs comes now with the `project.el` which is simpler and faster than projectile; could you consider to use it in order to make project change work without the projectile dependency?? 

Thanks in advance,
Ergus

**Comment by jiacai2050** [comment]
It's not hard to add it on your own
```

    (advice-add 'project-find-file
                :after 'dired-sidebar-follow-file)
```

**Comment by jojojames** [comment]
Added
