### ISSUE TITLE
Update from 02 March 2022 breaks dired-sidebar for me

### ISSUE THREAD

**Issue by QMeqGR** [jojojames/dired-sidebar#69]
On startup of emacs I now get the error:

Symbol's value as variable is void: dired-sidebar-face

This happened just after I updated dired-sidebar package today. Starting emacs with --debug-init gives the backtrace:

Debugger entered--Lisp error: (void-variable dired-sidebar-face)
  dired-sidebar-set-font()
  dired-sidebar-mode()
  dired-sidebar-show-sidebar(#<buffer :~/.emacs.d/source/>)
  dired-sidebar-toggle-sidebar()
  ehm-screen-setup1()
  (progn (defalias 'ehm-screen-setup1 #'(lambda nil "ehm startup layout with dired-sidebar" (interactive) (dashboard-refresh-buffer) (switch-to-buffer "*dashboard*") (delete-other-windows) (dired-sidebar-toggle-sidebar))) (global-set-key (kbd "C-c e 1") 'ehm-screen-setup1) (defalias 'ehm-screen-setup2 #'(lambda nil "ehm startup layout with treemacs" (interactive) (dashboard-refresh-buffer) (switch-to-buffer "*dashboard*") (delete-other-windows) (treemacs))) (global-set-key (kbd "C-c e 2") 'ehm-screen-setup2) (ehm-screen-setup1))
  (if (display-graphic-p) (progn (defalias 'ehm-screen-setup1 #'(lambda nil "ehm startup layout with dired-sidebar" (interactive) (dashboard-refresh-buffer) (switch-to-buffer "*dashboard*") (delete-other-windows) (dired-sidebar-toggle-sidebar))) (global-set-key (kbd "C-c e 1") 'ehm-screen-setup1) (defalias 'ehm-screen-setup2 #'(lambda nil "ehm startup layout with treemacs" (interactive) (dashboard-refresh-buffer) (switch-to-buffer "*dashboard*") (delete-other-windows) (treemacs))) (global-set-key (kbd "C-c e 2") 'ehm-screen-setup2) (ehm-screen-setup1)))
  eval-buffer(#<buffer  *load*> nil "/home/ehm/.emacs.d/init.el" nil t)  ; Reading at buffer position 47641
  load-with-code-conversion("/home/ehm/.emacs.d/init.el" "/home/ehm/.emacs.d/init.el" t t)
  load("/home/ehm/.emacs.d/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x1411d71a3ba21ebe>) #f(compiled-function () #<bytecode -0x1f3c6feddc0ad6f5>) t)
  command-line()
  normal-top-level()

===========
In  my init.el file I start up using the following code:

(when
    (display-graphic-p)
  ;; Set up the first screen I see the way I like.
  (defun ehm-screen-setup1 ()
    "ehm startup layout with dired-sidebar"
    (interactive)
    (dashboard-refresh-buffer)
    (switch-to-buffer "*dashboard*")
    (delete-other-windows)
    (dired-sidebar-toggle-sidebar)
    )
  (global-set-key (kbd "C-c e 1") 'ehm-screen-setup1)
  
  (defun ehm-screen-setup2 ()
    "ehm startup layout with treemacs"
    (interactive)
    (dashboard-refresh-buffer)
    (switch-to-buffer "*dashboard*")
    (delete-other-windows)
    (treemacs)
    )
  (global-set-key (kbd "C-c e 2") 'ehm-screen-setup2)
  
  ;; run the setup
  (ehm-screen-setup1))

**Comment by jojojames** [comment]
Probably related to https://github.com/jojojames/dired-sidebar/pull/67 

@DivineDominion any thoughts?

**Comment by DivineDominion** [comment]
Will experiment over the weekend!

**Comment by DivineDominion** [comment]
`emacs -Q` with just this works fine, but is of course rather bland:

```
(require 'dired-sidebar)
(dired-sidebar-toggle-sidebar)
```

Do you customize the `dired-sidebar-face`, and does the customization maybe rely on the fact that before the March update it wasn't a _face_ but a _variable_?
