### ISSUE TITLE
Rename toggle variables to either drop -p suffix or all adopt it?

### ISSUE THREAD

**Issue by DivineDominion** [jojojames/dired-sidebar#71]
Going through the code, I noticed that there's `dired-sidebar-one-instance-p` since #39; but other boolean toggles that are user-facing don't have the `-p` suffix, e.g.:

-  dired-sidebar-pop-to-sidebar-on-toggle-open
-  dired-sidebar-no-delete-other-windows
-  dired-sidebar-use-term-integration

My suggestion would be to rename `dired-sidebar-one-instance-p` to `dired-sidebar-use-one-instance` because that's least invasive (and I personally like the "speaking" variable names).

What do you think?

**Comment by jojojames** [comment]
Good suggestion, could make the change but also keep the old version as an alias to the new variable name. Open for PR.

**Comment by jojojames** [comment]
Changed
