### ISSUE TITLE
dired-sidebar doesn't work with default project.el behaviour

### ISSUE THREAD

**Issue by yxhuvud** [jojojames/dired-sidebar#73]
Since aed7e44b5a4ef3 dired-sidebard breaks against project.el with default project root behavior (ie, when project-root is not specified project.el will use the location of a version control repo in the path as the project root). However, dired-sidebar will always look after a `project-root`, which breaks if it isn't defined.

**Comment by jojojames** [comment]
Could you provide example values?

**Comment by jojojames** [comment]
What does (project-current) return when it's failing?

For example, in my dired-sidebar directory:

```
(project-current) ->
(vc Git "~/.emacs.d/straight/repos/dired-sidebar/")
```
```
(dired-sidebar-sidebar-root) ->
"~/.emacs.d/straight/repos/dired-sidebar/"
```


and in my *scratch* buffer:

```
(project-current) ->
nil
```

```
(dired-sidebar-sidebar-root) ->
"~/"
```

**Comment by yxhuvud** [comment]
`(project-current)` in a tracked repo returns `(vc . "~/path/to/repo")`.
`(project-current)` outside a repo returns nil. 

I care mostly about the former case - to access the path `(cdr (project-current))` seems to do it. I use that in some other places.

No idea how it behaves with `project-root` setup correctly, as I have found no instructions for how that function should work.

**Comment by jojojames** [comment]
If instead I do

```
(project-root (project-current))
```

?

e.g

```
(defun dired-sidebar-sidebar-root ()
  "Return directory using `projectile', `project' or current directory."
  (if (featurep 'projectile)
      (condition-case nil
          (if (fboundp 'projectile-project-root)
              (or (projectile-project-root) default-directory)
            default-directory)
        (error default-directory))
    ;; Use `project' if `projectile' is not loaded yet.
    ;; `projectile' is a big package and takes a while to load so it's better
    ;; to defer loading it as long as possible (until the user chooses).
    (dired-sidebar-if-let* ((project (project-current)))
        ;; https://github.com/jojojames/dired-sidebar/issues/61
        (if (eq (type-of project) 'ede-proj-project)
            ;; Found from calling: (eieio-class-slots 'ede-proj-project)
            (slot-value project 'directory)
          ;; e.g. (vc . "~/.emacs.d/straight/repos/dired-sidebar/")
          ;; or (vc Git "~/.emacs.d/straight/repos/dired-sidebar/")
          (project-root project))
      default-directory)))
```

Does it work for you?

**Comment by yxhuvud** [comment]
No. As noted above, `project-root ` is not defined, so trying to call it errors. Unfortunately the docs for project.el is not very clear if project-root is something that is supposed to be called by users or something that is called internally by `project-current`.

**Comment by jojojames** [comment]
From reading project.el, project-root should be defined by the backend which in this case is vc?

```
;; `project-root' must be defined for every project.


;; - Define new methods for some or all generic functions for this
;; backend using `cl-defmethod'.  A `project-root' method is
;; mandatory, `project-files' is recommended, the rest are optional.

(cl-defmethod project-root ((project (head vc)))
  (nth 2 project))

```

> As noted above, project-root is not defined, so trying to call it errors. 

Sounds good, to be clear, I'm not *super* sure what a lot of the subtlety here is so bear with me.

**Comment by yxhuvud** [comment]
Yeah, I also don't understand those parts. 

What I did find though, now that I've actually had time to dig into it, is that defining `dired-sidebar-sidebar-root` as
```
(defun dired-sidebar-sidebar-root ()
  "Return directory using `projectile', `project' or current directory."
  (if (featurep 'projectile)
      (condition-case nil
          (if (fboundp 'projectile-project-root)
              (or (projectile-project-root) default-directory)
            default-directory)
        (error default-directory))
    ;; Use `project' if `projectile' is not loaded yet.
    ;; `projectile' is a big package and takes a while to load so it's better
    ;; to defer loading it as long as possible (until the user chooses).
    (dired-sidebar-if-let* ((pr (project-current)))
        (if (fboundp 'project-root)
            (project-root pr)
          (cdr pr))
      default-directory)))
```
works for me.

**Comment by yxhuvud** [comment]
27.1, ie the version that is installed with `apt install emacs` on ubuntu 21.10. Perhaps vc provide a vc-root in newer emacs?

**Comment by jojojames** [comment]
27 should work... I was using it for a while...

Not super sure why your project-root isn't defined but I'm ok with a workaround PR with a comment (maybe linking back to this issue).
