### ISSUE TITLE
Font customization lost after version update

### ISSUE THREAD

**Issue by facundoolano** [jojojames/dired-sidebar#75]
Hi! I recently upgraded the version of dired-sidebar and I noticed it changed how the font looks, particularly it seems like it doesn't "inherit" the font I use elsewhere and it also ignores the height config I was using:

```elisp
(customize-set-variable 'dired-sidebar-use-custom-font t)
(customize-set-variable 'dired-sidebar-no-delete-other-windows t)
(setq dired-sidebar-face '(:height 120))

(custom-set-faces
 '(dired-directory ((t (:foreground "DodgerBlue3" :height 130 :background nil :weight normal))))
 '(all-the-icons-dired-dir-face ((((background light)) :foreground "DodgerBlue3" :height 130 :background nil :weight normal)))
 '(dired-header ((t (:foreground "gray" :height 120  :background nil :weight normal)))))
```

I suspect this is related to the recent face type commits, but I couldn't figure out how to adapt my config to it.

Before: 
<img width="229" alt="image" src="https://user-images.githubusercontent.com/1040941/183314521-5e42245a-df14-483a-b2ff-456043948db6.png">

After:
<img width="233" alt="image" src="https://user-images.githubusercontent.com/1040941/183313945-65005dd8-4370-4c77-81a4-e8a79491f285.png">

**Comment by jojojames** [comment]
```(customize-set-variable 'dired-sidebar-use-custom-font t)``` ?
