### ISSUE TITLE
Is there a way to customize "dired-sidebar" to show just in the side window? 

### ISSUE THREAD

**Issue by zhenhua-wang** [jojojames/dired-sidebar#77]
I enjoy using dired as a sidebar; however, I often switch to "dired-sidebar" in my main window and then kill it from the main window causing the sidebar to close as well. I'm wondering if there's a way to just show "directed-sidebar" on the side window (like in treemacs and neotree)? Thank you!

**Comment by zhenhua-wang** [comment]
Ah, I just find out that treemacs/neotree make their buffer hidden. So I can achieve similar effect by

``` lisp
  (defun zw/hide-buffer (orig-fun &rest args)
    (concat " "(apply orig-fun args)))
  (advice-add 'dired-sidebar-buffer-name :around #'zw/hide-buffer)
```

**Comment by zhenhua-wang** [comment]
Hi again,

After appending a space in front of the `dired-sidebar`, all file name's color were gone. Do you have any idea of what causing this (which function I should look at)? Thank you for any help

**Comment by jojojames** [comment]
A lot of the sidebar functions are using the name to find the bar I believe IIRC. I've been too lazy to fix it since I never rename the sidebar..

**Comment by jojojames** [comment]
Open to PR if anyone ever wants to fix the naming thing I mentioned above.
