### ISSUE TITLE
newest emacs build problem

### ISSUE THREAD

**Issue by arteen1000** [jojojames/dired-sidebar#83]
Hello!

I just built the newest emacs-29, and whenever I try to toggle the sidebar via `dired-sidebar-toggle-sidebar` I get:

```
Wrong type argument: stringp, (Git "<directory I am in>")
```

**Comment by ZelphirKaltstahl** [comment]
I am facing the same issue when trying to toggle the sidebar when the only 1 visible buffer is a Python buffer showing contents of an opened file.

**Comment by ZelphirKaltstahl** [comment]
To add more detail to this report:

```
GNU Emacs 29.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.37,
cairo version 1.16.0)
```

**Comment by jojojames** [comment]
Works for me on emacs 29.1 release.

**Comment by arteen1000** [comment]
I just re-built emacs off the latest emacs-29 branch and it is still an issue, exactly as described.

**Comment by jojojames** [comment]
Hi, I am using release and not the emacs 29 branch. Also using it on OSX.

**Comment by arteen1000** [comment]
Interesting. I just built the release version and am facing the same issue.

**Comment by jojojames** [comment]
I meant I am using the release version of emacs 29. Do you not have access to a release version of emacs?

**Comment by arteen1000** [comment]
I meant that I was originally using the latest version (from the constantly updated `emacs-29` branch), and when you mentioned you are using the release (emacs 29.1), I found the tar for that, built it, and tested on that as well.

**Comment by jojojames** [comment]
Hmnn, hard for me to help as I can't repro the issue on both a linux&mac setup with emacs 29. Maybe I'm missing something but not much I can do. :D 

Happy to take a PR if you figure something out.
