### ISSUE TITLE
Seamless 'C-o' (dired-display-file) behavior

### ISSUE THREAD

**Issue by ttybitnik** [jojojames/dired-sidebar#85]
Thank you for this package, first of all. It's exactly what I was trying to achieve manually with display-buffer-alist and so on.

The only feature I would like to add is the standard dired behavior of 'C-o' (dired-display-file). This command basically opens the file at point while keeping the pointer in the dired buffer. If there's already another window open, it uses that to display the file instead of creating a new window.

I've attempted mimic this behavior in dired-sidebar using the approaches below. For some reason, it keeps creating a new window instead of utilizing the already open one when you first run `dired-display-file`.

What I've tried so far:
1) `(define-key dired-sidebar-mode-map (kbd "C-o") 'dired-display-file)`
2) `(setq dired-sidebar-alternate-select-window-function 'dired-display-file)`

Both of them result in the same behavior of ignoring the window already opened. 

I'm not sure what I'm missing to solve this. Would appreciate this functionality or any guidance on achieving it.

**Comment by jojojames** [comment]
This one might work for you dired-sidebar-find-file-alt.

**Comment by ttybitnik** [comment]
Unfortunately, dired-sidebar-find-file-alt doesn't keep the cursor in the dired buffer as dired-display-file does.

Just in case anyone else needs it, I ended up doing this:

```elisp
(defun dired-sidebar-display-file()
  "Introduce the behavior of `dired-display-file' in `dired-sidebar'."
  (interactive)
  (dired-sidebar-find-file)
  (dired-sidebar-jump-to-sidebar))

;; Disable dired-sidebar-find-file-alt, a non vanilla behavior for dired C-o
(define-key dired-sidebar-mode-map (kbd "C-o") 'dired-sidebar-display-file)
(define-key dired-sidebar-mode-map (kbd "C-<return>") 'dired-sidebar-display-file)
```
Not optimal, but gets the job done.
