### ISSUE TITLE
File following not working

### ISSUE THREAD

**Issue by jvillasante** [jojojames/dired-sidebar#87]
When inside a project (using project.el not projectile) file following is not working, I get the following error when invoking `dired-sidebar-toggle-sidebar` with an open file: `dired-sidebar-point-at-file: Search failed: "^.*[[:space:]]Common$"`

**Comment by jvillasante** [comment]
After some investigation this is related to `golden-ratio`. Looks like adding `(add-to-list 'golden-ratio-exclude-modes 'dired-sidebar-mode)` solves the problem.

**Comment by jvillasante** [comment]
Found the issue, looks like it has to do with how `dired-listing-switches` is set, the issue happens when it is set like follows:
```
(setq dired-listing-switches "-alhvF --group-directories-first")
```

But disappears when it is set like follows:
```
(setq dired-listing-switches
          "-l --almost-all --human-readable --group-directories-first --no-group")
```

Maybe this should be documented? It looks like `dired-listing-switches` has a saying on that "$" that is appended to `path-regex` in `dired-sidebar-point-at-file`.

**Comment by jojojames** [comment]
Could be related? https://github.com/jojojames/dired-sidebar/commit/04b39fb52021832eed4bf9bb748f46892afaf62e
