### ISSUE TITLE
How to hide symlink destination

### ISSUE THREAD

**Issue by ydzhou** [jojojames/dired-sidebar#88]
Showing up symlink destination making tree too wide to be displayed properly. How can I turn it off?

**Comment by jojojames** [comment]
https://github.com/Fuco1/dired-hacks/issues/125

https://github.com/jojojames/dired-sidebar/issues/7

dired-sidebar sets dired-hide-details-hide-symlink-targets to nil. You could try setting it to t to disable the symlinks but the misplaced nodes might mess you up.
