### ISSUE TITLE
doesn't work anymore on emacs 29

### ISSUE THREAD

**Issue by MikHulk** [jojojames/dired-sidebar#89]
Since I have upgraded to emacs 29 dired-sidebar yield many warnings but did work. Howver, Since the last update of dired-siderbar it doesn't work. 

It displays folder but it's impossible to unfold dubdir and I get this message:

"dired-current-directory: No subdir-alist in "

I noticed this message when I launch it from a folder too:

"dired-sidebar-mode: Symbol’s value as variable is void: dired-sidebar-face"

**Comment by jojojames** [comment]
I'm using Emacs 29 day to day on both my home & work computer.

**Comment by MikHulk** [comment]
So I guess you don't have these warnings and dired-sidebar works for you. It doesn't for me since the upgrade. I had to change to an alternative. I have warnings for many other things. Most of the time they continue to work, but in this case the folder doesn't fold/unfold.

**Comment by MikHulk** [comment]
Do you use emacs 29 with tree-sitter ?

**Comment by Aneeqasif** [comment]
dired sidebar is not working for me when i press key like C or enter it says dired-current-directory: `No subdir-alist in :~/Sync/org/ [3 times]`
