### ISSUE TITLE
Useful package, but apparently seems like conflicting with `which-key`!

### ISSUE THREAD

**Issue by zenny** [jojojames/dired-sidebar#92]
@jojojames Thanks for such a useful package. Yet it appears conflicting with `which-key` as I have discussed in https://github.com/pprevos/emacs-writing-studio/issues/13 and https://github.com/pprevos/emacs-writing-studio/issues/15

Thanks and have a nice weekend,
Cheers,
/z

**Comment by jojojames** [comment]
Works for meTM, probably something in your config. Without a reproducible plain config, not much I can do.
