### ISSUE TITLE
Resizing the sidebar

### ISSUE THREAD

**Issue by shirgho** [jojojames/dired-sidebar#94]
Thank you for making the dired-sidebar package.

I have an issue: mainly that I cannot resize the sidebar. i.e. set its width.
I believe this is intentional, but can we override this setting?

**Comment by ukiran03** [comment]
`customize'
(use-package dired-sidebar
  :custom
  (dired-sidebar-window-fixed nil)
  (dired-sidebar-width 25))

**Comment by shirgho** [comment]
Thank you, I had found the dired-sidebar-window-fixed option, forgot to update here. Now also using the default width option you suggest now.
