### ISSUE TITLE
Icons not showing anymore - Emacs 30.0.92

### ISSUE THREAD

**Issue by iris-garcia** [jojojames/dired-sidebar#96]
I'm not sure what has changed, but after updating my emacs and doom to the latest, it looks like dired-sidebar do not show icons anymore.

I have tried the different theme options (icons, ascii, nerd) with no luck:

![image](https://github.com/user-attachments/assets/d0644352-e733-41d3-a0d9-c4d99c67bcfc)

**Comment by jojojames** [comment]
It looks like you have icons... in your picture, looks like 'nerd icons.

You also need to provide more than just a screenshot.

Provide a recipe I can reproduce, feel free to reopen.

**Comment by iris-garcia** [comment]
Hi @jojojames, thanks for replying. 
It is hard to give a good recipe with my current setup (doom emacs) it looks quite simple in my config tho:

in `packages.el`:
```
(package! dired-sidebar)
```

In the Config:
```
(use-package! dired-sidebar
  :config
  (setq dired-sidebar-use-custom-font nil)
  (setq dired-sidebar-theme 'icons)
  (defun ig/dired-sidebar-modeline()
    (interactive)
    (setq-local mode-line-format " Dired-Sidebar"))
  (ig-keys/define-key 'normal 'dired-sidebar-mode-map "g" 'revert-buffer)
  (add-hook 'dired-sidebar-mode-hook 'ig/dired-sidebar-modeline))
```
The hook and the define-key are not even related to dired-sidebar.


Screenshot of theme `'icons`:
![image](https://github.com/user-attachments/assets/942bdb24-fa00-4689-93bb-83c09c6ac67d)

Right before the update of Emacs, I had icons for the folders and files shown in the sidebar.

I have also checked that I have all-the-icons installed and working
![image](https://github.com/user-attachments/assets/72171845-33bc-4791-9538-8aec79ece901)

**Comment by jojojames** [comment]
> It is hard to give a good recipe with my current setup (doom emacs) it looks quite simple in my config tho:

Without a recipe, it's impossible to debug your setup, and doom is anything but simple.

You probably need https://github.com/jtbm37/all-the-icons-dired .

I'd recommend biting the bullet and just reading the code otherwise, adding breakpoints or print statements.

**Comment by iris-garcia** [comment]
Thank you @jojojames, the weird thing is in Dired, it shows the icons well.

I'll try to debug it.

**Comment by jojojames** [comment]
I just added nerd-icons support which you can try too.

```
(use-package nerd-icons :defer t)
(use-package nerd-icons-dired
  :commands (nerd-icons-dired-mode))
(setq dired-sidebar-theme 'nerd-icons)

```

to the relevant places.

**Comment by iris-garcia** [comment]
It worked like a charm, thank you very much @jojojames.
